name: Create Git tag
description: Create Git tag for current commit
version: 2

inputs:
  tagName:
    description: Git tag name
    required: true
  message:
    description: Git tag message
    required: false
  committerName:
    description: Git user.name
    required: false
    default: 'github-actions[bot]'
  committerEmail:
    description: Git user.email
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  forcePush:
    description: Set to 'true' to enable force push
    required: false
    default: 'true'
  dryRun:
    description: Set to 'true' to disable Git push
    required: false
    default: 'false'

outputs:
  result:
    value: ${{steps.commit.outputs.result}}
    description: |
      'remote-changed' - remote repository branch has been changed, push-back is skipped;
      'tagged-successfully' - tag has been created successfully;

runs:
  using: composite
  steps:
  - name: Configure git, commit & push
    id: commit
    shell: bash
    env:
      TAG_MESSAGE: ${{inputs.message}}
    run: |
      set -euo pipefail

      echo Configuring Git user...
      git config user.name "${{inputs.committerName}}"
      git config user.email "${{inputs.committerEmail}}"

      echo Creating tag...
      if [[ -n "${TAG_MESSAGE:-}" ]]; then
        echo "Creating annotated tag (with message)..."
        git tag --force -a "${{inputs.tagName}}" -m "$TAG_MESSAGE"
      else
        echo "Creating lightweight tag (no message)..."
        git tag --force "${{inputs.tagName}}"
      fi

      echo "Pushing${{fromJSON(inputs.forcePush) && ' (with --force)' || ''}}..."
      set +e
      push_log_file="$(mktemp)"
      git push ${{fromJSON(inputs.dryRun) && '--dry-run' || ''}} ${{fromJSON(inputs.forcePush) && '--force' || ''}} origin "refs/tags/${{inputs.tagName}}" 2>&1 | tee "$push_log_file"
      push_exit=${PIPESTATUS[0]}
      set -e

      if [[ $push_exit -eq 0 ]]; then
        echo Push succeeded.
        echo "result=pushed-successfully" >> $GITHUB_OUTPUT
      elif grep -q "non-fast-forward" "$push_log_file" || grep -q "\[rejected\]" "$push_log_file"; then
        echo "Push rejected (remote changed or conflicting tag)."
        echo "result=remote-changed" >> $GITHUB_OUTPUT
      else
        echo Push failed for some other reason.
        exit 1
      fi
